#!/usr/bin/python

import urllib2
from xml.etree import ElementTree

# Set up page request and then pull data
page = "https://mellowd.co.uk/ccie/bgp/bgp.xml"
header = {'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64)\
           AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11'} 
request = urllib2.Request(page, headers=header)
page = urllib2.urlopen(request)

# Extract the ipv4 and ipv6 values
tree = ElementTree.parse(page)
rootElem = tree.getroot()
ipv4_element = rootElem.find("ipv4")
ipv6_element = rootElem.find("ipv6")
ipv4 = ipv4_element.text.strip(' \n\t')
ipv6 = ipv6_element.text.strip(' \n\t')

if int(ipv4) == 0:
    print "v4 session is down"
else:
    print "v4 count is",ipv4
if int(ipv6) == 0:
    print "v6 session is down"
else:
    print "v6 count is",ipv6
